#!/bin/bash

active=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true).specialWorkspace.name')

if [[ -n "$active" ]]; then
	if [[ "$active" == "special:"* ]]; then
		active=${active#special:}
	elif [[ "$active" == "special" ]]; then
		active=""
	fi
	hyprctl dispatch togglespecialworkspace "$active"
fi

case "$1" in
-w)
	hyprctl dispatch workspace "$2"
	;;
-x)
	hyprctl dispatch focusworkspaceoncurrentmonitor "$2"
	;;
*)
	echo "Usage: $0 {workspace <name> | focus <name>}"
	exit 1
	;;
esac
