#!/bin/bash

# Usage: focuswindow tofi/rofi/wofi

window_list=$(hyprctl -j clients | jq -r '.[] | "\(.title) | \(.address)"')

declare -A window_map
updated_window_list=""
index=1

while IFS= read -r line; do
    window_address=${line##* | }
    window_map[$index]=$window_address
    updated_window_list+="$index | ${line% | *}"$'\n'
    let index=index+1
done <<<"$window_list"

selected_window=$(echo -e "$updated_window_list" | $1)

window_id=${selected_window%% | *}
window_address=${window_map[$window_id]}

if [ -z "$window_address" ]; then
    echo "No window selected."
    exit 1
fi

hyprctl dispatch focuswindow "address:$window_address"
