#!/usr/bin/env bash

# TODO: Make better screenrecord script

rofi_command="rofi -markup -markup-rows -theme $HOME/.config/rofi/themes/launcher.rasi"
datetime=$(date +"%Y-%m-%d %I-%M-%S")
dir="$HOME/Videos/Screen-Recordings"

# Icons
icon1="$HOME/.config/rofi/images/camera-movie.svg"
icon2="$HOME/.config/rofi/images/timer.svg"

screen="  Record Desktop"
area="  Record Area"
window="  Record Window"
infivearea="  Record Area in 5s"
infive="  Record in 5s"

# Stop wf-recorder if it's running
stop_wf_recorder() {
	if pgrep -x wf-recorder >/dev/null; then
		pkill -x wf-recorder
		exit 0
	fi
}

# Notify and view recording
notify_view() {
	notify-send -u low "Copied to clipboard."
	echo "$dir/Screen Recording from ${datetime}.mkv"
	#    if [[ -e "$dir/Screen Recording from ${datetime}.mkv" ]]; then
	#        echo "$dir/Screen Recording from ${datetime}.mkv"
	#        action=$(notify-send --action="default,openss" -u low "Screen Recording Saved.")
	#        case "$action" in
	#        "default")
	#            xdg-open "$dir/Screen Recording from ${datetime}.mkv"
	#            ;;
	#        esac
	#    else
	#        notify-send -u low "Screen Recording Deleted."
	#    fi
}

# Countdown
countdown() {
	for sec in $(seq $1 -1 1); do
		notify-send -t 1000 --replace=699 -i $icon2 "Recording in : $sec"
		sleep 1
	done
}

# Recording
recordnow() {
	sleep 0.5 && wf-recorder -g "0,0 1920x1080" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy <$dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

record5() {
	countdown '5'
	sleep 1 && wf-recorder -g "0,0 1920x1080" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy <$dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

record5area() {
	countdown '5'
	sleep 1 && wf-recorder -g "$(slurp -b#0f0f0f78 -c#cc7765 -w4)" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy <$dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

recordwin() {
	geometry=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
	sleep 1 &
	wf-recorder -g "${geometry}" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy <$dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

recordarea() {
	wf-recorder -g "$(slurp -b#0f0f0f78 -c#cc7765 -w4)" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy <$dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

# Ensure directory exists
if [[ ! -d "$dir/" ]]; then
	mkdir -p "$dir/"
fi

# Argument parsing
case "$1" in
--stop)
	stop_wf_recorder
	;;
--recordnow)
	recordnow
	;;
--record5)
	record5
	;;
--record5area)
	record5area
	;;
--recordwin)
	recordwin
	;;
--recordarea)
	recordarea
	;;
--launcher)
	# Variable passed to rofi
	options="$screen\n$area\n$window\n$infivearea\n$infive"

	chosen="$(echo -e "$options" | $rofi_command -p 'Screen Recording' -dmenu -selected-row 0)"
	case $chosen in
	$screen)
		recordnow
		;;
	$area)
		recordarea
		;;
	$window)
		recordwin
		;;
	$infive)
		record5
		;;
	$infivearea)
		record5area
		;;
	esac
	;;
*)
	echo "Usage: $0 [--stop | --recordnow | --record5 | --record5area | --recordwin | --recordarea | --launcher]"
	;;
esac
