#!/usr/bin/env bash

#rofi_command="rofi -theme launcher -p 'screen-rec' -dmenu -selected-row 0"
tofi_command="tofi --height 280 --width 300 --prompt-text=screen-rec:"
datetime=$(date +"%Y-%m-%d %I-%M-%S")
dir="$HOME/media/videos/screen-rec"

# Recording options
options=(
	" Record Desktop"
	" Record Area"
	" Record Window"
	" Record Area in 5s"
	" Record in 5s"
)

# Ensure directory exists
mkdir -p "$dir"

# Stop wf-recorder if running
stop_wf_recorder() {
	pkill -x wf-recorder && exit 0
}

# Notify and copy recording path to clipboard
notify_view() {
	notify-send -u low "Recording saved" "Copied to clipboard."
	wl-copy <"$dir/screen_rec_${datetime}.mkv"
}

# Countdown function
countdown() {
	for sec in $(seq "$1" -1 1); do
		notify-send -t 1000 --replace=699 "Recording in: $sec"
		sleep 1
	done
}

# Start recording with given geometry
start_recording() {
	wf-recorder -g "$1" -f "$dir/screen_rec_${datetime}.mkv" && notify_view
}

# Argument parsing
case "$1" in
--stop)
	stop_wf_recorder
	;;
--recordnow)
	start_recording "0,0 1920x1080"
	;;
--record5)
	countdown 5
	start_recording "0,0 1920x1080"
	;;
--record5area)
	countdown 5
	start_recording "$(slurp -b#0f0f0f78 -c#cc7765 -w4)"
	;;
--recordwin)
	geometry=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
	start_recording "$geometry"
	;;
--recordarea)
	start_recording "$(slurp -b#0f0f0f78 -c#cc7765 -w4)"
	;;
--launcher)
	chosen=$(printf "%s\n" "${options[@]}" | $tofi_command)
	case "$chosen" in
	" Record Desktop") start_recording "0,0 1920x1080" ;;
	" Record Area") start_recording "$(slurp -b#0f0f0f78 -c#cc7765 -w4)" ;;
	" Record Window") geometry=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"') && start_recording "$geometry" ;;
	" Record in 5s")
		countdown 5
		start_recording "0,0 1920x1080"
		;;
	" Record Area in 5s")
		countdown 5
		start_recording "$(slurp -b#0f0f0f78 -c#cc7765 -w4)"
		;;
	esac
	;;
*)
	echo "Usage: $0 [--stop | --recordnow | --record5 | --record5area | --recordwin | --recordarea | --launcher]"
	;;
esac
