#!/bin/bash
# Get the current location in the shell
current_location=$(pwd)

# List of excluded paths
excluded_paths=(
    "$HOME" "$HOME/" "$HOME/Desktop" "$HOME/Downloads" "$HOME/Documents"
    "/" "/bin" "/boot" "/dev" "/etc" "/lib" "/proc" "/root" "/sbin" "/sys" "/usr" "/var"
)

# Check if the current location is one of the excluded paths
if [[ "$1" != "-o" ]]; then
    for path in "${excluded_paths[@]}"; do
        if [[ "$current_location" == "$path" ]]; then
            echo "Exited. One of the excluded paths ($path)."
            notify-send "Exited." "One of the excluded paths ($path)."
            exit 0
        fi
    done
fi

# Default sorting method (Newest to Oldest)
sort_command="sort -r -n -k1,1"

# Function to display sorting menu and update sort_command
choose_sorting_method() {
    sorting_method=$(echo -e "Newest to Oldest\nOldest to Newest\nAlphabetical (A-Z)\nAlphabetical (Z-A)" | rofi -dmenu -i -p "Sorting" -theme ~/.config/rofi/themes/launcher3.rasi)
    case $sorting_method in
    "Newest to Oldest")
        sort_command="sort -r -n -k1,1"
        ;;
    "Oldest to Newest")
        sort_command="sort -n -k1,1"
        ;;
    "Alphabetical (A-Z)")
        sort_command="sort"
        ;;
    "Alphabetical (Z-A)")
        sort_command="sort -r"
        ;;
    *)
        exit 0
        ;;
    esac
}

# Function to find and sort images
display_images() {
    if [[ "$1" == "-o" ]]; then
        maxdepth="-maxdepth 1"
    else
        maxdepth=""
    fi

    if [[ $sort_command == *"-n -k1,1"* ]]; then
        images=$(find "$current_location" $maxdepth -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -printf "%T@ %p\n" | $sort_command | cut -d' ' -f2-)
    else
        images=$(find "$current_location" $maxdepth -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | $sort_command)
    fi

    # Display a menu with the list of images (only file names from subdirectories)
    selected_image=$(echo "$images" | while IFS= read -r img; do
        relative_path="${img#$current_location/}"
        echo -en "$relative_path\0icon\x1f$img\n"
    done | rofi -dmenu -i -p "$current_location" -kb-custom-1 "Ctrl+s" -theme ~/.config/rofi/themes/sig.rasi)

    # Check if custom keybinding was pressed
    if [[ $? -eq 10 ]]; then
        choose_sorting_method
        display_images "$1" # Reload images with new sorting
    else
        # If an image is selected
        if [[ -n $selected_image ]]; then
            full_path="$current_location/$selected_image"
            # Display a menu with options for the selected image
            action=$(echo -e "Open\nCopy image\nRename\nOpen in GIMP\nCopy path\nDrag & drop" | rofi -dmenu -i -p "Select action" -theme ~/.config/rofi/themes/launcher3.rasi)
            case $action in
            "Open")
                xdg-open "$full_path"
                ;;
            "Copy image")
                mime_type=$(file --mime-type -b "$full_path")
                wl-copy -t "$mime_type" <"$full_path"
                ;;
            "Rename")
                new_name=$(rofi -dmenu -i -p "New name" -theme ~/.config/rofi/themes/launcher3.rasi -theme-str "listview { enabled: false;}")
                if [[ -n $new_name ]]; then
                    extension="${full_path##*.}"
                    mv "$full_path" "$(dirname "$full_path")/$new_name.$extension"
                fi
                ;;
            "Open in GIMP")
                gimp "$full_path"
                ;;
            "Copy path")
                echo -n "$full_path" | wl-copy
                ;;
            "Drag & drop")
                ripdrag "$full_path"
                ;;
            *)
                echo "Exited"
                ;;
            esac
        fi
    fi
}

display_images "$1"
