#!/bin/bash

# Get the current location in the shell
current_location=$(pwd)

# List of excluded paths
excluded_paths=(
    "$HOME" "$HOME/" "$HOME/Desktop" "$HOME/Downloads" "$HOME/Documents"
    "/" "/bin" "/boot" "/dev" "/etc" "/lib" "/proc" "/root" "/sbin" "/sys" "/usr" "/var"
)

# Check if the current location is one of the excluded paths
for path in "${excluded_paths[@]}"; do
    if [[ "$current_location" == "$path" ]]; then
        echo "Exited. One of the excluded paths ($path)."
        notify-send "Exited." "One of the excluded paths ($path)."
        exit 0
    fi
done

if [[ "$1" == "-o" ]]; then
    # Find all images only in the current location
    images=$(find "$current_location" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \))
else
    # Find all images in the current location and its subdirectories
    images=$(find "$current_location" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \))
fi

# Display a menu with the list of images (only file names from subdirectories)
selected_image=$(for img in $images; do
    # Remove the current location from the full path to get the relative path
    relative_path="${img#$current_location/}"
    echo -en "$relative_path\0icon\x1f$img\n"
done | rofi -dmenu -i -p "$current_location" -theme ~/.config/rofi/themes/sig.rasi)

# If an image is selected
if [[ -n $selected_image ]]; then
    full_path="$current_location/$selected_image"
    
    # Display a menu with options for the selected image
    action=$(echo -e "Open\nCopy image\nChange name\nOpen in GIMP\nCopy path" | rofi -dmenu -i -p "Select action" -theme ~/.config/rofi/themes/launcher3.rasi)
    
    case $action in
        "Open")
            xdg-open "$full_path"
            ;;
        "Copy image")
            mime_type=$(file --mime-type -b "$full_path")
            wl-copy -t "$mime_type" < "$full_path"
            ;;
        "Change name")
            new_name=$(rofi -dmenu -i -p "New name" -theme ~/.config/rofi/themes/launcher3.rasi -theme-str "listview { enabled: false;}")
            if [[ -n $new_name ]]; then
                extension="${full_path##*.}"
                mv "$full_path" "$(dirname "$full_path")/$new_name.$extension"
            fi
            ;;
        "Open in GIMP")
            gimp "$full_path"
            ;;
        "Copy path")
            echo -n "$full_path" | wl-copy
            ;;
        *)
            echo "Exited"
            ;;
    esac
fi